export const USER_ROLES = {
  STOCKMASTER: 'STOCKMASTER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  WAREHOUSE_STAFF: 'WAREHOUSE_STAFF',
};

export const OTP_TYPES = {
  SIGNUP: 'SIGNUP',
  PASSWORD_RESET: 'PASSWORD_RESET',
  LOGIN: 'LOGIN',
};

export const MOVEMENT_TYPES = {
  RECEIPT: 'RECEIPT',
  DELIVERY: 'DELIVERY',
  TRANSFER: 'TRANSFER',
  ADJUSTMENT: 'ADJUSTMENT',
};

export const MOVEMENT_STATUS = {
  DRAFT: 'DRAFT',
  WAITING: 'WAITING',
  READY: 'READY',
  DONE: 'DONE',
  CANCELED: 'CANCELED',
};

export const LOCATION_TYPES = {
  WAREHOUSE: 'WAREHOUSE',
  STORE: 'STORE',
  TRANSIT: 'TRANSIT',
  DAMAGED: 'DAMAGED',
  QUARANTINE: 'QUARANTINE',
};

export const NOTIFICATION_TYPES = {
  LOW_STOCK: 'LOW_STOCK',
  MOVEMENT_STATUS: 'MOVEMENT_STATUS',
  COUNT_ASSIGNED: 'COUNT_ASSIGNED',
  SYSTEM_ALERT: 'SYSTEM_ALERT',
  APPROVAL_REQUIRED: 'APPROVAL_REQUIRED',
};

export const AUDIT_ACTIONS = {
  CREATE: 'CREATE',
  UPDATE: 'UPDATE',
  DELETE: 'DELETE',
  APPROVE: 'APPROVE',
  REJECT: 'REJECT',
  COMPLETE: 'COMPLETE',
};

export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
};

export const PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
};
